name: Create Azure AD App Registrations

on:
  workflow_dispatch:

jobs:
  aadAppRegistration:
    name: Create Azure AD App Registrations
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Github checkout
        uses: actions/checkout@v2

      - name: Get Subscription ID and Resource Group Name
        uses: azure/CLI@v1
        id: context
        with:
          azcliversion: 2.0.72
          inlineScript: |
            echo "::set-output name=subscriptionId::$(az account list --query [0].id --output tsv)"
            echo "::set-output name=resourceGroupName::$(az group list --query [0].name --output tsv)"

      - name: Get Azure resource names
        id: resourceNames
        uses: whiteducksoftware/azure-arm-action-js@v4
        with:
          scope: resourcegroup
          subscriptionId: ${{ steps.context.outputs.subscriptionId }}
          resourceGroupName: ${{ steps.context.outputs.resourceGroupName }}
          templateLocation: "./src/Infrastructure/Cloud/Arm/resource-names.json"
          parameters: appNamePrefix=${{ secrets.APP_NAME_PREFIX }}

      - name: Generate unique id for API App scope.
        id: guidGen
        run: echo "::set-output name=scopeId::$(uuidgen)"

      - name: Create Azure Ad App Registration for API App.
        env:
          API_APP_URL: "https://api.${{ steps.resourceNames.outputs.webAppName }}.azurewebsites.net"
        uses: azure/CLI@v1
        id: apiAppReg
        with:
          azcliversion: 2.0.72
          inlineScript: |
            MANIFEST_FILE="./src/Infrastructure/Cloud/Aad/aad-api-app-manifest.json"
            APP_ID=$(az ad app create --display-name "${{secrets.APP_NAME_PREFIX}} API App" \
            --identifier-uris $API_APP_URL \
            --oauth2-allow-implicit-flow false \
            --app-roles @$MANIFEST_FILE --query appId --output tsv)

            DEFAULT_SCOPE=$(az ad app show --id $APP_ID | 
            jq '.oauth2Permissions[0].isEnabled = false' | 
            jq -r '.oauth2Permissions')
            az ad app update --id $APP_ID --set oauth2Permissions="$DEFAULT_SCOPE"
            az ad app update --id $APP_ID --set oauth2Permissions='[]'

            NEW_SCOPE=$(cat $MANIFEST_FILE |
              jq -r --arg SCOPE_ID ${{ steps.guidGen.outputs.scopeId }} '(.oauth2Permissions[] | .id )=$SCOPE_ID' |
              jq -r .oauth2Permissions)
            az ad app update --id $APP_ID --set oauth2Permissions="$NEW_SCOPE"

            az ad sp create --id $APP_ID

            echo "::set-output name=appId::$APP_ID"
            echo "::set-output name=scopeId::$SCOPE_ID"

      - name: Create Azure Ad App Registration for Client app.
        env:
          CLIENT_APP_URL: "https://${{ steps.resourceNames.outputs.webAppName }}.azurewebsites.net"
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            APP_ID=$(az ad app create --display-name "${{secrets.APP_NAME_PREFIX}} Client App" \
            --identifier-uris $CLIENT_APP_URL \
            --oauth2-allow-implicit-flow true \
            --reply-urls $CLIENT_APP_URL "$CLIENT_APP_URL/auth.html" \
            --query appId --output tsv)

            az ad app permission add --id $APP_ID \
            --api 00000003-0000-0000-c000-000000000000 \
            --api-permissions e1fe6dd8-ba31-4d61-89e7-88639da4683d=Scope

            az ad app permission add --id $APP_ID \
            --api ${{ steps.apiAppReg.outputs.appId }} \
            --api-permissions ${{ steps.guidGen.outputs.scopeId }}=Scope

            DEFAULT_SCOPE=$(az ad app show --id $APP_ID |
            jq '.oauth2Permissions[0].isEnabled = false' |
            jq -r '.oauth2Permissions')
            az ad app update --id $APP_ID --set oauth2Permissions="$DEFAULT_SCOPE"
            az ad app update --id $APP_ID --set oauth2Permissions='[]'

            az ad sp create --id $APP_ID

            az ad app permission grant --id $APP_ID --api 00000003-0000-0000-c000-000000000000 
            az ad app permission grant --id $APP_ID --api ${{ steps.apiAppReg.outputs.appId }}
